[build]
  functions = "netlify/functions"
  publish = "public"

# Scheduled cron job
[[scheduled]]
  name = "sendMessage"
  cron = "0 7 * * *"   # Runs daily at 7:00 UTC â†’ 8:00 Nigeria Time
  function = "sendMessage"
